INSERT INTO issues
    (
        id,
        title,
        description,
        priority,
        status,
        department_id
    )
VALUES
    (
        103,
        'Streetlight failure',
        'Three lights are not working',
        'HIGH',
        'ASSIGNED',
        2
    );

    CREATE TABLE issue_audit_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

        issue_id BIGINT NOT NULL,

        action VARCHAR(100) NOT NULL,

        created_at TIMESTAMP WITH TIME ZONE NOT NULL,

        CONSTRAINT fk_audit_issue
            FOREIGN KEY (issue_id)
            REFERENCES issues(id)
    );