spring.application.name=civicflow

# ---------------------------------------------------------
# Database
# ---------------------------------------------------------

spring.datasource.url=jdbc:postgresql://localhost:5432/civicflow
spring.datasource.username=postgres
spring.datasource.password=112

# ---------------------------------------------------------
# JPA / Hibernate
# ---------------------------------------------------------

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ---------------------------------------------------------
# Server
# ---------------------------------------------------------

server.port=8080

# ---------------------------------------------------------
# CivicFlow application timezone
# ---------------------------------------------------------

civicflow.timezone=${CIVICFLOW_TIMEZONE:UTC}

# ---------------------------------------------------------
# Spring Boot Actuator
# ---------------------------------------------------------

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ---------------------------------------------------------
# Application information
# ---------------------------------------------------------

info.app.name=CivicFlow
info.app.description=Community issue management platform
info.app.version=1.0.0

# ---------------------------------------------------------
# Logging
# ---------------------------------------------------------

logging.level.com.civicflow=INFO

# ---------------------------------------------------------
# JWT
# ---------------------------------------------------------

civicflow.jwt.secret=${CIVICFLOW_JWT_SECRET:change-this-development-secret-to-a-long-random-value}

civicflow.jwt.expiration-ms=${CIVICFLOW_JWT_EXPIRATION_MS:3600000}