package com.civicflow.exception;

public enum ApiErrorCode {

    VALIDATION_FAILED,

    ISSUE_NOT_FOUND,

    INVALID_ISSUE_STATUS_TRANSITION,

    EMAIL_ALREADY_EXISTS,

    IDEMPOTENCY_KEY_CONFLICT,

    RATE_LIMIT_EXCEEDED,

    ACCESS_DENIED,

    AUTHENTICATION_REQUIRED,

    ISSUE_MODIFIED_CONCURRENTLY,

    INTERNAL_SERVER_ERROR
}